TOKEN = '6247630241:AAGvWHnG1jNcGp_XjjHBvjrtTY961yCdRz4'

DATABASE_USER = "root"
DATABASE_PASSWORD = "allsafe1"
DATABASE_HOST = "localhost"
DATABASE_NAME = "car_db"

# Ссылка на базу данных
MYSQL_URL = f"mysql+pymysql://{DATABASE_USER}:{DATABASE_PASSWORD}@{DATABASE_HOST}/{DATABASE_NAME}"